### ISSUE TITLE
Вёрстка: Чат

### ISSUE THREAD

**Issue by Pospelove** [Pospelove/skymp-gamemode#1]
**[Скачать .psd](https://github.com/Pospelove/skymp-gamemode/files/3100130/Chat_SkyMP.zip)**

Стандартный вид чата. Так выглядит чат, когда игрок только вошёл в игру.
![image](https://user-images.githubusercontent.com/37947786/56447676-0ff44400-630a-11e9-80f7-a77eb365060c.png)

Эффект при наведении.
![image](https://user-images.githubusercontent.com/37947786/56447755-809b6080-630a-11e9-87d3-7634cc9e11cd.png)

Адаптивность вкладок, т.е. перенос вкладок, которые не влезают, не следующую строчку.
7 столбиков чата умещаются в один ряд. При 8 чат сдвигается вниз.
![image](https://user-images.githubusercontent.com/37947786/56447697-27cbc800-630a-11e9-8d67-af10304bd6db.png)
![image](https://user-images.githubusercontent.com/37947786/56447680-15ea2500-630a-11e9-9e75-1c0956960844.png)

При нажатий на вкладку чат, строки ввода нет. Канал "Чат" является общим чатом, куда сливаются сообщения из всех остальных каналов. Поэтому input здесь отсутствует.
![image](https://user-images.githubusercontent.com/37947786/56447695-23071400-630a-11e9-909c-6ae6b5f80445.png)

Появление теста с правого бока.
![image](https://user-images.githubusercontent.com/37947786/56448418-408aac80-630f-11e9-91ee-9c00ad109c73.png)

Отдаление старых сообщений при прокрутке текста.
![image](https://user-images.githubusercontent.com/37947786/56448368-c22e0a80-630e-11e9-9537-2695849923db.png)

**Comment by rrov** [comment]
Взялся делать
